FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/project/

COPY ./requirements/common.txt ./

RUN \
    pip install gunicorn && \
    pip install --no-cache-dir -r common.txt

COPY ./back/ ./

RUN python manage.py migrate

RUN python manage.py collectstatic --no-input --clear
