# Generated by Django 2.2.10 on 2021-01-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Answer as text'), ('select-one', 'Answer as select one'), ('select-multiple', 'Answer as select multiple')], default='text', max_length=64)),
            ],
        ),
    ]
